### ISSUE TITLE
NameError: global name '__class__' is not defined

### ISSUE THREAD

**Issue by kiliakis** [blond-admin/BLonD#117]
Randy wrote:

Hello,
I'm trying to get the master branch working on my computer and keep running in to this error.
(I have the v1.19 running with no problems so far)

```Traceback (most recent call last):
  File "EX_03_RFnoise.py", line 85, in <module>
    long_tracker = RingAndRFTracker(rf_params, beam)
  File "/home/BLonD-master/trackers/tracker.py", line 231, in __init__
    self.logger = logging.getLogger(__class__.__name__)
NameError: global name '__class__' is not defined
```

I was wondering if I made a mistake on setting up BLonD on my computer or am I missing something?
Also is there an example available to generate a matched bunch to an RF bucket using emittance rather than the bunch lengths ? 

Thank you!

Best Regards,
Randy

**Comment by kiliakis** [comment]
After a quick check, I saw that the exception only appears in python2. So a quick-fix would be to use python3 instead :)

Python2 needs ```self.__class__``` instead. We can propagate this change to the code but the question is whether we are going to support python2 and 3 or python3 only.

**Comment by kiliakis** [comment]
Not supporting python2.7 anymore, we can close this issue and safely use `self.__class__.name`.
