### ISSUE TITLE
Update synchrotron_frequency_distribution() for TC12 to work

### ISSUE THREAD

**Issue by htimko** [blond-admin/BLonD#30]
Update the call of FullRingAndRF.potential_well_generation() from utilities.synchrotron_frequency_distribution() since arguments have changed.

When I run TC12, I get the following error:

Traceback (most recent call last):
  File "C:\Users\blond\git\BLonD\__TEST_CASES\main_files\TC12_synchrotron_frequency_distribution.py", line 94, in <module>
    particleDistributionFreq, synchronous_time = synchrotron_frequency_distribution(beam, full_tracker)
  File "C:\Users\blond\git\BLonD\trackers\utilities.py", line 66, in synchrotron_frequency_distribution
    main_harmonic_option = main_harmonic_option)
TypeError: potential_well_generation() got an unexpected keyword argument 'turn'

**Comment by dquartul** [comment]
fixed thanks
